### ISSUE TITLE
return result instead of just printing it.

### ISSUE THREAD

**Issue by jaydouble** [shuque/dane#2]
Hi, 

in tlsa.go there is a function to print the result:
https://github.com/shuque/dane/blob/312d7e1649e76c02367c6db26ba4db6ea91dbad6/tlsa.go#L81-L98

Is it possible to make it returning the result instead?
I want to make some docker container that mail when something goes wrong, now it can only mail: it failed. If I can use this function to see what is failing, it is a bit more informative.

**Comment by shuque** [comment]
Apologies for seeing your request so late.

I've added a new ResultsString() method to do this. https://github.com/shuque/dane/blob/master/tlsa.go#L87
